# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeb73fdb55f937999f51c013d936abb012b361608c36440df378f9d9fe2b75c4a492c5e80e7587c02577b734b78883015bed7531f6c49d97667a2d9cbc375811

test:
  secret_key_base: cda7ea65c3a96277e902d09bfea649011677910fc03b641c5a78fa6f8c9d98e344f29c79872cc16b500ef0ca3a0c6d1eeb6cda7df4515550cd4532e0f430df09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
